#!/bin/sh
set -e

[ -d /dev/net ] ||
    mkdir -p /dev/net
[ -c /dev/net/tun ] ||
    mknod /dev/net/tun c 10 200

touch /var/log/pritunl.log
touch /var/run/pritunl.pid
/bin/rm /var/run/pritunl.pid

build_mongodb_uri() {
  MONGODB_URI="mongodb://$1:$2/pritunl"
}

## start a local mongodb instance if no mongodb specified through env
if [ -z "$MONGODB_URI" ]; then
  if [ -n "$MONGO_PORT_27017_TCP_ADDR" ] &&
    [ -n "$MONGO_PORT_27017_TCP_PORT" ]; then
    build_mongodb_uri $MONGO_PORT_27017_TCP_ADDR $MONGO_PORT_27017_TCP_PORT
  else
    /usr/bin/mongod -f /etc/mongod.conf &
    sleep 70 ## for mongo to allocate journals
    build_mongodb_uri "localhost" "27017"
  fi
fi

cat << EOF > /etc/pritunl.conf
{
    "debug": false,
    "bind_addr": "0.0.0.0",
    "port": 9700,
    "log_path": "/var/log/pritunl.log",
    "temp_path": "/tmp/pritunl_%r",
    "local_address_interface": "auto",
    "mongodb_uri": "$MONGODB_URI",
    "server_key_path": "/var/lib/pritunl/pritunl.key",
    "static_cache": true,
    "server_cert_path": "/var/lib/pritunl/pritunl.crt",
    "www_path": "/usr/share/pritunl/www"
}
EOF

/usr/bin/pritunl start &
[ "$1" ] && exec "$@"

