#!/bin/sh
set -e

[ -d /dev/net ] ||
    mkdir -p /dev/net
[ -c /dev/net/tun ] ||
    mknod /dev/net/tun c 10 200

touch /var/log/pritunl.log
touch /var/run/pritunl.pid
/bin/rm /var/run/pritunl.pid
/usr/bin/mongod -f /etc/mongodb.conf &
sleep 70 ## for mongo to allocate journals
/usr/bin/pritunl start &
[ "$1" ] && exec "$@"

